### ISSUE TITLE
visiting http://localhost:8081  shows nothing

### ISSUE THREAD

**Issue by wanghaisheng** [airbnb/airpal#123]
I have successfully run presto server against  mysql.you can see when I try to access http://localhost:8081 ,it seems airpal is ok,but there is nothing shows
<img width="1264" alt="qq20150722-1 2x" src="https://cloud.githubusercontent.com/assets/2363295/8817953/08009a7e-306d-11e5-9a3c-05aa0140a992.png">
<img width="1261" alt="qq20150722-2 2x" src="https://cloud.githubusercontent.com/assets/2363295/8817975/408150d2-306d-11e5-875d-1079ffbb30cf.png">

**Comment by tonywutao** [comment]
it may caused by app.js 404,  can not load js. 

try this:
export NODE_ENV='development'
then rebuild
./gradlew clean showJar -Dairpal.useLocalNode

**Comment by wanghaisheng** [comment]
it seems the problem is the same as https://github.com/airbnb/airpal/issues/97

**Comment by wanghaisheng** [comment]
edwin@edwindeMacBook-Pro.local:/Users/edwin/workspace/airpal  git:(master*) $ ./gradlew clean shadowJar -Dairpal.useLocalNode
:cleanAssets UP-TO-DATE
:clean
:nodeSetup SKIPPED
:installAssets
npm WARN package.json airpal@0.0.1 No license field.
gulp-notify@2.2.0 node_modules/gulp-notify
├── lodash.template@3.6.2 (lodash._basecopy@3.0.1, lodash._basevalues@3.0.0, lodash.templatesettings@3.1.0, lodash._reinterpolate@3.0.0, lodash._basetostring@3.0.1, lodash.escape@3.0.0, lodash.restparam@3.6.1, lodash._isiterateecall@3.0.9, lodash.keys@3.1.2)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── node.extend@1.1.5 (is@3.0.1)
└── node-notifier@4.2.3 (shellwords@0.1.0, growly@1.2.0, minimist@1.1.2, semver@4.3.6, which@1.1.1, lodash.clonedeep@3.0.1, cli-usage@0.1.1)
:buildAssets
[10:44:40] Using gulpfile ~/Documents/workfolder/workspace/airpal/src/main/resources/assets/gulpfile.js
[10:44:40] Starting 'browserify'...
[10:44:40] Bundling app.js...
[10:44:40] Bundling plugin.js...
[10:44:40] gulp-notify: [Compile Error] not implemented
[10:44:40] gulp-notify: [Compile Error] not implemented
[10:44:40] Bundled app.js in 23 ms
[10:44:40] Bundled plugin.js in 24 ms
[10:44:40] Finished 'browserify' after 138 ms
:compileJava
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
:processResources
:classes
:shadowJar

BUILD SUCCESSFUL

Total time: 1 mins 36.153 secs

**Comment by wanghaisheng** [comment]
edwin@edwindeMacBook-Pro.local:/Users/edwin/workspace/airpal  git:(master*) $ ./gradlew clean shadowJar
:cleanAssets UP-TO-DATE
:clean
:nodeSetup UP-TO-DATE
:installAssets
:buildAssets
[11:05:15] Using gulpfile ~/Documents/workfolder/workspace/airpal/src/main/resources/assets/gulpfile.js
[11:05:15] Starting 'browserify'...
[11:05:15] Bundling app.js...
[11:05:15] Bundling plugin.js...
[11:05:21] Bundled plugin.js in 6.15 s
[11:05:30] Bundled app.js in 15 s
[11:05:30] Finished 'browserify' after 15 s
:compileJava
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
:processResources
:classes
:shadowJar

BUILD SUCCESSFUL

Total time: 59.781 secs
