### ISSUE TITLE
DB migrate not creating jobs tables.

### ISSUE THREAD

**Issue by rogersmarin** [airbnb/airpal#125]
After running db migrate these are the only tables in the airpal schema:

job_outputs     
job_tables       
saved_queries    
schema_version   
tables      

This is causing queries to fail with the following exception:

Exception thrown when executing query: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'airpal.jobs' doesn't exist

**Comment by bkyryliuk** [comment]
https://github.com/airbnb/airpal/blob/master/src/main/resources/db/migration/mysql/V1__Create_jobs_table.sql
DB creation is here. I was not able to reproduce the bug. 
please feel free to reopen it if the issue is still present.
@rogersmarin ^^
