### ISSUE TITLE
Changing the awsCredentials system to use a provider

### ISSUE THREAD

**Issue by J314Y** [airbnb/airpal#135]
There are two functions (provideAWSCredentials and provideAmazonS3Client(AWSCredentials awsCredentials) ) that currently are set to manually taking in an accesskey or a secretAccessKey. I was wondering if we could push a functionality that would take credentials from an AWSCredentialsProvider for those who have the IAM roles set.

These functions are found in:
airpal/src/main/java/com/airbnb/airpal/modules/AirpalModule.java

**Comment by yixu34** [comment]
Btw the recommendation from Amazon is to use `DefaultAWSCredentialsProviderChain`: http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html
