### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by sangeeta28** [airbnb/airpal#154]
Hi, we are restricted from downloading using - Downloading https://services.gradle.org/distributions/gradle-2.2.1-all.zip.
So I have downloaded gradle manually and installed it. But when I run the command 
./gradlew -Dairpal.prestoVersion=0.119 clean shadowJar
it still goes and looks for downloading. How do I change this in gradlew script to make it point to my already installed gradle? Thanks!

**Comment by sangeeta28** [comment]
Looks like the script doesn't work very well when behind proxies. Had to manually download all the jars and then install.

**Comment by yanyani989** [comment]
For gradle-wrapper I had to download the gradle-xxx-all.zip manually then modify gradle-wrapper.properties to use the local zip.

Try to install local nodejs/npm and configure proxy for them should help:
`sudo yum -y install node
sudo yum -y install npm
npm config set http-proxy http://<proxyHost:port>
npm config set https-proxy http://<proxyHost:port>
npm set strict-ssl false

./gradlew clean shadowJar -Dhttp.proxyHost=<proxyHost> -Dhttp.proxyPort=<proxyPort> -Dhttps.proxyHost=<proxyHost> -Dhttps.proxyPort=<proxyPort> -Dairpal.useLocalNode`

**Comment by bkyryliuk** [comment]
@sangeeta28 that's right, your question is more related to the gradle.
There are a couple stackoverflow discussions:
  * http://stackoverflow.com/questions/8938994/gradlew-behind-a-proxy
  * http://stackoverflow.com/questions/5991194/gradle-proxy-configuration
I hope they may be helpful to you.
