### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by boss999** [airbnb/airpal#157]
I don't understand this, can you give me a detailed said? Thanks

allGroup = com.airbnb.shiro.UserGroup
allGroup.groups = all
allGroup.permissions = access, read:*:*, write:*:*
allGroup.defaultConnector = hive
allGroup.defaultSchema = default
allGroup.timeout = 40m
allGroup.accessLevel = User

**Comment by bkyryliuk** [comment]
I am not sure that I have a full context. Could you please update the issue topic and the message to have more details about the issue ?
Please reopen is if you still need help. @boss999
