### ISSUE TITLE
no viable alternative at input 'number'

### ISSUE THREAD

**Issue by rootcss** [airbnb/airpal#173]
These queries work fine in presto-cli but fails on AirPal:
1. select a.first_name name, a.phone_number number, a.email email  from table_name_1 a left join table_name_2 b ON a.id = b.user_id where a.id NOT IN (select c.user_id from table_name_2 c) AND a.p_name='XYZ';
2.  select a.first_name AS name, a.phone_number AS number, a.email AS email  from table_name_1 a left join table_name_2 b ON a.id = b.user_id where a.id NOT IN (select c.user_id from table_name_2 c) AND a.p_name='XYZ';

This one works fine in both presto and AirPal.
select a.first_name, a.phone_number, a.email  from table_name_1 a left join table_name_2 b ON a.id = b.user_id where a.id NOT IN (select c.user_id from table_name_2 c) AND a.p_name='XYZ';

Is AS not supported by AirPal, which it should I guess.

**Comment by bkyryliuk** [comment]
**number** is the reserved keyword
try:
 select a.first_name AS name, a.phone_number AS **"number"**, a.email AS email from table_name_1 a left join table_name_2 b ON a.id = b.user_id where a.id NOT IN (select c.user_id from table_name_2 c) AND a.p_name='XYZ';

**Comment by rootcss** [comment]
Thank you @bkyryliuk
