### ISSUE TITLE
I always get "Catalog hive does not exist"

### ISSUE THREAD

**Issue by warrenca** [airbnb/airpal#96]
[SOLVED]

I have run everything but I am not sure why I can't query and it always return "Catalog hive does not exist". What am i missing here?

Thanks.

----
In presto-server-0.96/etc/catalog dir, I created a connector named "hive.properties". zzzz

**Comment by andykram** [comment]
Were you able to solve the issue?

**Comment by warrenca** [comment]
I was able to solve, the problem is in prestodb. I actually created a hive.properties but the settings are for mysql. I think it is not the proper way.

I think somewhere in airpal configuration you can set the "hive" to other values like "mysql", "postgres", "jmx", etc. or it is currently hard coded as "hive"?

**Comment by andykram** [comment]
Oh I see what happened. I think we used to have more defaults in the `reference.yml`, but we tried to simplify it. What you can do in Airpal is specify a `prestoCatalog` option (defined [here](https://github.com/airbnb/airpal/blob/master/src/main/java/com/airbnb/airpal/AirpalConfiguration.java#L40)) which is the default catalog to use. I'll make an issue to better document all the supported configuration options.

**Comment by andykram** [comment]
Opened https://github.com/airbnb/airpal/issues/100 to raise the issue and remind myself to better document that config options

**Comment by warrenca** [comment]
nice thanks :smile:
