### ISSUE TITLE
Dependency installation instructions

### ISSUE THREAD

**Issue by TomClarkson** [airbnb/airpal#98]
The install is failing for me with the following error
Grgit : Unsupported major.minor version 51.0 

I am using yosemite and I have java version details as follows

java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

**Comment by hshoff** [comment]
Hi @TomClarkson, thanks checking out Airpal. Looks like Grgit requires java 7 or higher: https://github.com/ajoberstar/grgit/issues/35

**Comment by andykram** [comment]
Yep, as @hshoff and [the reqs section](https://github.com/airbnb/airpal#requirements) says, Java 7+ is required. Please let us know if you have any issues building with Java 7+!
